import OpenAI from "openai";
import { zodTextFormat } from "openai/helpers/zod";
import { z } from "zod";

// Structured extraction of a historical invoice PDF, used by the migration
// script (scripts/migrate-historical.ts). Works on PDFs generated by any
// prior bookkeeping system (Xolo, Quipu, hand-rolled templates, etc.) —
// the model figures out the layout.
//
// Single-line invoices (the monthly billing pattern this app uses) extract
// cleanly. Multi-line invoices return the first line; the migration script
// emits a warning so the operator can spot-check.

const InvoiceExtractionSchema = z.object({
  number: z
    .string()
    .nullable()
    .describe(
      "Invoice number / reference as printed (e.g. 'FACT-2025-00007', 'INV-2024-12', '2025/045'). null if not findable."
    ),
  date: z
    .string()
    .describe("Issue date in YYYY-MM-DD. Use the issued/emitted date, not payment received date."),
  dueDate: z
    .string()
    .nullable()
    .describe("Payment due date in YYYY-MM-DD. null if the invoice doesn't state one."),
  description: z
    .string()
    .describe(
      "Description of the (single) line item. If the invoice has multiple lines, return the first or summarise."
    ),
  hours: z
    .number()
    .describe(
      "Quantity of the line item — typically hours billed. If the invoice uses a different unit (e.g. 'days', 'units'), return the numeric quantity as-is."
    ),
  unit: z
    .string()
    .describe('Unit string the quantity refers to. "h" for hours, "d" for days, "u" for generic units.'),
  hourlyRateCents: z
    .number()
    .int()
    .describe(
      "Unit price in cents (EUR). Multiply euro rate by 100 and round. e.g. €60.00/h → 6000."
    ),
  netCents: z
    .number()
    .int()
    .describe("Subtotal in cents (EUR), before VAT. e.g. €4140.00 → 414000."),
  vatCents: z.number().int().describe("Total VAT amount in cents. 0 if VAT-exempt or intra-EU."),
  totalCents: z.number().int().describe("Final invoice total in cents (net + VAT)."),
  vatExempt: z
    .boolean()
    .describe(
      "true if the invoice is VAT-exempt (intra-EU services under art. 25, reverse charge, etc.). false for normal VAT-bearing invoices."
    ),
  currency: z.string().describe('ISO currency code, usually "EUR". Default "EUR" if unclear.'),
});

export type InvoiceExtraction = z.infer<typeof InvoiceExtractionSchema>;

let _client: OpenAI | null = null;
function client(): OpenAI {
  if (!_client) {
    if (!process.env.OPENAI_API_KEY) throw new Error("OPENAI_API_KEY not set");
    _client = new OpenAI();
  }
  return _client;
}

export async function parseInvoicePdf(args: {
  pdfBuffer: Buffer;
  filename: string;
}): Promise<InvoiceExtraction> {
  const base64 = args.pdfBuffer.toString("base64");
  const fileData = `data:application/pdf;base64,${base64}`;

  const response = await client().responses.parse({
    model: "gpt-5.4-mini",
    input: [
      {
        role: "user",
        content: [
          {
            type: "input_text",
            text:
              "Extract invoice fields from this PDF. All amounts are in cents (multiply euros by 100, round to nearest cent). " +
              "If the invoice has multiple lines, use the first line for hours/unit/hourlyRateCents, and sum all lines for netCents/totalCents. " +
              "vatExempt=true when the PDF says things like 'exempt', 'reverse charge', 'inversión del sujeto pasivo', 'art. 25', or shows 0% VAT on intra-EU services.",
          },
          { type: "input_file", filename: args.filename, file_data: fileData },
        ],
      },
    ],
    text: {
      format: zodTextFormat(InvoiceExtractionSchema, "invoice"),
    },
  });

  if (!response.output_parsed) throw new Error("Model did not return parsed output");
  return response.output_parsed;
}
